### ISSUE TITLE
not support ccTLD

### ISSUE THREAD

**Issue by casparant** [michimani/chrome-tab-ex#17]
Hi, when using this extension I realized it does not handle ccTLD correctly in ingore sub-domain mode, e.g.: tabs under 'google.com.hk' would be grouped under 'com' tab, which is obviously not right.

Reproducible in 1.2.2 installed from Chrome web store, by the way. 

Thanks!

**Comment by michimani** [comment]
@casparant  
Thank you very much for using my extension and for your feedback!

As you've pointed out, this behavior is not correct. I will fix it.

Just to confirm this, are you assuming that `google.com.hk` is included in the `google` tab group?

**Comment by casparant** [comment]
> @casparant Thank you very much for using my extension and for your feedback!
> 
> As you've pointed out, this behavior is not correct. I will fix it.
> 
> Just to confirm this, are you assuming that `google.com.hk` is included in the `google` tab group?

Correct, IMO `google.com.hk` should go to `google` tab group. And if I open `google.com.hk` `google.co.jp` and `google.co.uk` pages in the same window, I'm definitely ok if they go to the same `google` tab group.  btw, thanks again for your hard working on such a productivity tool :-)

Caspar

**Comment by michimani** [comment]
Thanks for replying.

> Also, if I open the google.com.hk google.co.jp and google.co.uk pages in the same window, it's definitely OK as long as they go to the same google tab group.

And thank you very much for providing a concrete example.
Please wait for a while as I will fix it to work like this.

**Comment by michimani** [comment]
@casparant  

I've fixed the issue you pointed out and submitted a fix to the Chrome Web Store. It will usually be released to the store in a few days, and you can then use the fixed version by updating your existing extensions.

If you want to check the behavior immediately, download the source.zip of v1.2.3 from the release page of this repository and upload it with developer mode enabled for your Chrome extension.

Thanks to your feedback, this extension has become an even better tool. Thank you very much!

**Comment by michimani** [comment]
v1.2.3, which fixes this issue, has been released to the Google Chrome Store, so you can update your installed extensions as well.
Thanks!

**Comment by casparant** [comment]
Confirmed latest Google Chrome Store version fixed this issue. Thanks!
